import NavEvent from "./Event";

const wait = (ms: number) => {

  return new Promise(resolve => {
    setTimeout(() => {
      resolve(Math.random());
    }, ms);
  });
};


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>


        {children}
        <NavEvent></NavEvent>

      </body>
    </html>
  )
}
